ENABLE_QCN 0
USE_DYNAMIC_PFC_THRESHOLD 0

PACKET_PAYLOAD_SIZE 9000

SIMULATOR_STOP_TIME 100000000.00

CC_MODE 0
ERROR_RATE_PER_LINK 0.0000
L2_CHUNK_SIZE 8000
L2_ACK_INTERVAL 5
L2_BACK_TO_ZERO 0

ENABLE_TRACE 0

BUFFER_SIZE 52428800

MON_START 0
MON_END 0
QP_MON_INTERVAL 0
QLEN_MON_INTERVAL 0
BW_MON_INTERVAL 0
